package com.kdob.piq.ai.domain.model

enum class PipelineStatus {
    NEW,
    ARTIFACT_GENERATION_IN_PROGRESS,
    WAITING_ARTIFACT_APPROVAL,
    FAILED,
    TOPIC_TREE_APPROVED,
    QUESTIONS_APPROVED,
    ANSWERS_APPROVED,
    SHORT_ANSWERS_APPROVED
}
