package com.kdob.piq.ai.domain.model

enum class PipelineStatus {
    NEW,
    DRAFT,
    PENDING_FOR_ARTIFACT_APPROVAL,
    APPROVED,
    FAILED,
    QUESTIONS_PENDING_FOR_APPROVAL,
    QUESTIONS_APPROVED,
    TOPIC_TREE_GENERATED,
    TOPIC_TREE_APPROVED,
    QUESTIONS_GENERATED,
    ANSWERS_GENERATED,
    ANSWERS_APPROVED,
    SHORT_ANSWERS_GENERATED,
    SHORT_ANSWERS_APPROVED,
    PUBLISHED
}