package com.kdob.piq.ai.domain.model

enum class PipelineStatus {
    NEW,
    FAILED,
    TOPIC_TREE_GENERATED,
    TOPIC_TREE_APPROVED,
    QUESTIONS_GENERATED,
    QUESTIONS_APPROVED,
    ANSWERS_GENERATED,
    ANSWERS_APPROVED,
    SHORT_ANSWERS_GENERATED,
    SHORT_ANSWERS_APPROVED
}
